.Dd February 8, 2022
.Dt JEFF 7
.Sh NAME
.Nm jeff
.Nd software engineer (he/him)
.Sh DESCRIPTION
.Nm jeff
is a software engineer with experience building distributed systems, automating
fleets of linux servers, writing APIs, creating web frontends, wrangling cloud
technology, and mentoring and managing other engineers.

He has utilized AWS, GCP, and on-prem servers in production, including using
kubernetes and docker. He tempers his bias for action with consideration for
operational excellence via monitoring, alerting, and observability.

He is most proficient with python, go, and bash, and he dabbles in
rust, javascript, typescript, c#, and haskell.
.Sh INTERESTS
.Nm jeff
loves to learn and grow with others. He hopes to work with smart, friendly
people who share knowledge together while solving interesting and important
problems.
.Sh HISTORY
.Bl -width '1' \" start of work history

.Bl -tag -width "yyyy-yyyy" -compact \" start of employer
.It 2021-2022
.Bl -tag -width "" -compact
.Sy Recurse Center
.Bl -tag -compact -width "1" -offset "2n" \" start of individual roles
.It Recurser
Studied rust, haskell, shaders, and more. See
.Sx EXAMPLES
section.
.El \" end of individual roles
.El
.El \" end of employer

.Bl -tag -width "yyyy-yyyy" -compact \" start of employer
.It 2019-2021
.Bl -tag -compact
.Sy Cruise
.Bl -tag -compact -width "1" -offset "2n" \" start of individual roles
.It Engineering Manager, PaaS
Managed the team responsible for providing internal kubernetes services and devops tooling
.Pp
.It Senior Software Engineer, PaaS
Operated kubernetes clusters and automated deployment workflows for clusters and their users
.El \" end of individual roles
.El
.El \" end of employer

.Bl -tag -width "yyyy-yyyy" -compact \" start of employer
.It 2017-2019
.Bl -tag -compact
.Sy Lightsale, Inc.
.Bl -tag -compact -width "1" -offset "2n" \" start of individual roles
.It Co-founder
Built VR app, ecommerce frontend and backend APIs, CI/CD, monitoring, and
alerting on GKE, along with half of everything else that needed to happen.
.El \" end of individual roles
.El
.El \" end of employer

.Bl -tag -width "yyyy-yyyy" -compact \" start of employer
.It 2014-2017
.Bl -tag -compact
.Sy Quantcast
.Bl -tag -compact -width "1" -offset "2n" \" start of individual roles
.It Systems Engineer
Iterated on eng-wide monitoring, alerting, dns, ci/cd, and engineering best practices.
.Pp
.It Production Engineer
Ran bare-metal and hybrid batch processing clusters.
.El \" end of individual roles
.El
.El \" end of employer

.Bl -tag -width "yyyy-yyyy" -compact \" start of employer
.It 2012-2014
.Bl -tag -compact
.Sy Coupa Software
.Bl -tag -compact -width "1" -offset "2n" \" start of individual roles
.It Cloud Operations Engineer
Operated hundreds of Ruby on Rails apps across dev, sandbox, and production servers.
.Pp
.It Customer Care Engineer
Fielded support requests. Wrote scripts for operations engineers to review and
run. Found and reported defects.
.El \" end of individual roles
.El
.El \" end of employer

.Bl -tag -width "yyyy-yyyy" -compact \" start of employer
.It 2007-2011
.Bl -tag -compact
.Sy University of California, Santa Cruz
.Bl -tag -compact -width "1" -offset "2n"
.It Bachelors of Science, Economics
.El \" end of individual roles

.El \" end of work history

.Sh EXAMPLES
.Bl -tag compact
.It { TODO }
.El
.Sh SEE ALSO
.Bl -compact
.It
github.com/jeffawang
.It
linkedin.com/in/jeffawang
.It
jeffawang.com
.El
.Sh AUTHORS
Jeff Wang
