.Dd February 8, 2022
.Dt JEFF 7
.Sh NAME
.Nm jeff
.Nd software engineer (he/him)
.Sh DESCRIPTION
.Nm jeff
is a software engineer with experience operating distributed systems,
automating fleets of linux servers, writing APIs, creating web frontends,
wrangling cloud technology, and mentoring and managing other engineers. He
loves to learn and enjoys diverse and curiously-minded company.
.Sh TECHNOLOGIES
.Bl -tag -compact -width "1"
.It Languages
.It
Python, Go, Bash, TypeScript, JavaScript, C# (learning Rust, Haskell, GLSL,
WGSL)

.It Systems and tools
.It
GNU/Linux, Kubernetes, Terraform, Docker, Puppet, AWS, GCP, on-prem
.El
.Sh HISTORY
.Bl -tag -width "" -offset "-2n"
.It
.Sy Voltus

.Bl -tag -compact -width "1" -offset "1n"
.It
.Sy Senior Software Engineer
(Sep 2022 - Now)
.Bl -compact -width "1" -offset "-1n" -bullet -offset "2n"
.El
.El
.Bl -tag -width "" -offset "-2n"
.It
.Sy Recurse Center

.Bl -tag -compact -width "1" -offset "1n"
.It
.Sy Recurser
(Nov 2021 - Feb 2022)
.Bl -compact -width "1" -offset "-1n" -bullet -offset "2n"
.It
Learned Haskell, Rust, GLSL, and WGSL
.It
Created a collaborative poetry webapp with React and Next.js
.It
Built a shader live-coding tool with TypeScript and a website to showcase the shaders
.It
Used Rust and shaders to generate visual art from oscilloscope music
.It
Wrote a small ascii game in Go which takes place on a cube
.El
.El

.Bl -tag -width "" -compact -offset "-2n"
.It
.Sy Cruise

.Bl -tag -compact -width "1" -offset "1n"
.It
.Sy Engineering Manager, PaaS
(Jul 2020 - Sep 2021)
.Bl -compact -width "1" -offset "-1n" -bullet -offset "2n"
.It
Managed 5 engineers (new-grad through senior)
.It
Owned eng-wide mission-critical kubernetes-based PaaS (GKE and on-prem)
.It
Delivered self-service infrastructure provisioning and deployment abstractions to engineering teams
.It
Organized an cross-team hackathon and created new tools to gain and visualize insight on toil
levels. Made stickers.
.It
Facilitated and participated in code and design reviews
.El
.It

.Sy Senior Software Engineer, PaaS
(Apr 2019 - Jul 2020)
.Bl -compact -width "1" -bullet -offset "2n"
.It
Operated eng-wide mission-critical kubernetes-based PaaS (GKE and on-prem), part of the time
as tech lead.
.It
Automated provisioning by writing Kubernetes operators in Go, reducing engineering effort for new infrastructure from
one week to one minute.
.It
Created docs and self-service APIs in Go to categorically eliminate support requests.
.It
Supported team with coaching, code reviews, and pair programming
.It
Co-hosted cross-team hackathon and created a UX-focused service management API
and CLI, a la heroku
.It
24/7 on-call rotation
.El
.El
.El

.Bl -tag -width "" -compact -offset "-2n"
.It
.Sy Lightsale, Inc.

.Bl -tag -compact -width "1" -offset "1n"
.It
.Sy Co-founder
(Oct 2017 - Apr 2019)
.Bl -compact -width "1" -bullet -offset "2n"
.It
Built frontends for VR and web
.It
Built ecommerce backend APIs for payments, users, orders, products, etc.
.It
Built CI/CD
.It
Built monitoring and alerting
.It
Set up GKE
.It
Did half of everything else alongside the one other co-founder
.El
.El

.Bl -tag -width "" -compact -offset "-2n"
.It
.Sy Quantcast

.Bl -tag -compact -width "1" -offset "1n"
.It
.Sy System Engineer
(Jan 2016 - Apr 2017)
.Bl -compact -width "1" -bullet -offset "2n"
.It
Evaluated, chose, and migrated to new monitoring and metrics system
.It
Developed tools to automate scalable cloud deployments
.It
Built out company-wide ticketing and alerting system
.It
Managed eng-wide CI/CD systems
.It
Migrated DNS from on-prem to hybrid cloud
.It
24/7 on-call rotation
.El
.It

.Sy Production Engineer
(May 2014 - Jan 2016)
.Bl -bullet -compact -width "1" -offset "2n"
.It
Automated and scaled bare metal MapReduce cluster
.It
Implemented migration from on-prem to hybrid aws infrastructure
.It
Hacked on config management and observability with puppet, ganglia, nagios, and python
.It
24/7 on-call rotation
.El
.El
.El

.Bl -tag -width "" -compact -offset "-2n"
.It
.Sy Coupa Software

.Bl -tag -compact -width "1" -offset "1n"
.It
.Sy Cloud Operations Engineer
(Jun 2013 - May 2014)
.Bl -bullet -compact -width "1" -offset "2n"
.It
Monitored and maintains hundreds of rails application instances in production
.It
Hacked on automation scripts and server templates (bash, chef)
.It
24/7 on-call rotation
.El
.It

.Sy Customer Care Engineer
(Jul 2012 - Jun 2013)
.Bl -bullet -compact -width "1" -offset "2n"
.It
Wrote scripts for operations engineers to review and run
.It
Interacted with customers to answer questions and configure instances
.It
Found defects in the application and submitted bug reports
.El
.El
.El

.Sh SEE ALSO
.Bl -compact
.It
github.com/jeffawang
.It
linkedin.com/in/jeffawang
.It
jeffawang.com
.El
.Sh AUTHOR
Jeff Wang
